### ISSUE TITLE
QURAN TEXT ISSUE showing small Mim (إقلاب ميم) in wrong places

### ISSUE THREAD

**Issue by vipafattal** [islamic-network/alquran.cloud#14] opened 2020-05-16 22:46 UTC
As far as I know, l مْ + ب cause to convert م to ن, and in this places Quran notation should show small Mim, but There are numerous of places where this case (مْ + ب) doesn't happen but there is no Mim, I check original Quran text I didn't find them.

I'm listing below some of this issue: 
رُكَّعًۭا سُجَّدًۭا يَبْتَغُونَ

تَبْصِرَةًۭ وَذِكْرَىٰ لِكُلِّ

أَءِذَا مِتْنَا وَكُنَّا تُرَابًۭا ۖ

 إِنَّ ٱللَّهَ غَفُورٌۭ رَّحِيمٌ

ذَكَرٍۢ وَأُنثَىٰ وَجَعَلْنَٰكُمْ شُعُوبًۭا

إِنَّ أَكْرَمَكُمْ عِندَ ٱللَّهِ أَتْقَىٰكُمْ ۚ إِنَّ ٱللَّهَ عَلِيمٌ خَبِيرٌۭ

ٱجْتَنِبُوا۟ كَثِيرًۭا مِّنَ

 ٱلظَّنِّ إِثْمٌۭ ۖ وَلَا 

إِنَّ ٱللَّهَ تَوَّابٌۭ رَّحِيمٌۭ

And the list goes on...

From: http://api.alquran.cloud/v1/juz/26/quran-uthmani

**Comment by meezaan** [comment] 2020-05-17 05:02
Al Salaamu Alaykum.

I think you should look for this in the tajweed edition, not the uthmanic edition, as this is specific to tajweed and not to written Arabic in the Qur'an.

**Comment by vipafattal** [comment] 2020-05-17 06:16
Shouldn't Quran Uthmani match the original Quran notation as quran-tajweed add complexity not required needed for just showing original Quran purposes?

**Comment by meezaan** [comment] 2020-05-17 06:37
I do not think it was never intended to match it.

Even today, you can buy physical Qur'ans with Uthmanic text that do not contain the twajeed notation - in fact, I have several of them - Alhamdulillah!

I don't think the purpose of every phyiscal Qur'an is recitation out aloud - the intention of many versions is to read it to contemplate the meaning - so the specific tajweed pronunciation markings do not necessarily add value there.

I think whilst have quran-tajweed may add complexity from a programming point of view, the tajweed markings don't belong in the uthmanic edition, semantically speaking.

**Comment by vipafattal** [comment] 2020-05-17 13:10
Fair enough, I understand that Quran Uthmani doesn't have to same the original Quran, but as far as accuracy is concerned Quran Uthmani doesn't have to look the same the original but also - as I think - mustn't add wrong Arabic punctuation or Quranic punctuation.

**Comment by meezaan** [comment] 2020-05-17 14:04
Agreed!

**Comment by vipafattal** [comment] 2020-05-20 10:31
So any chances to make progress in this issue in the future.

**Comment by meezaan** [comment] 2020-05-20 11:17
Sorry, I thought the agreement was to not change the uthmani edition because the tajweed edition already has the tajweed pronunication marks. Is this edition adding anything that is wrong?

**Comment by vipafattal** [comment] 2020-05-20 11:22
Yes it does when it's showing Iqlab (إقلاب) Mim in not Iqlab places.

**Comment by meezaan** [comment] 2020-05-20 11:55
Can you share 3 or 4 verse references numbers with me, please, and I will investigate.

Reopening the issue.

**Comment by vipafattal** [comment] 2020-05-20 13:12
Please head to the firt comment I add few of them they all show wrong Iqlab Mim.

**Comment by meezaan** [comment] 2020-05-20 19:29
I need ayah numbers, please.

**Comment by vipafattal** [comment] 2020-05-20 20:04
There are many in juz' 26 and this Ayat are obtained from pages 514-517
numbers:
رُكَّعًۭا سُجَّدًۭا يَبْتَغُونَ  4612

4638 تَبْصِرَةًۭ وَذِكْرَىٰ لِكُلِّ

4633 أَءِذَا مِتْنَا وَكُنَّا تُرَابًۭا ۖ

4626 إِنَّ ٱللَّهَ غَفُورٌۭ رَّحِيمٌ

4625 ذَكَرٍۢ وَأُنثَىٰ وَجَعَلْنَٰكُمْ شُعُوبًۭا

4625 إِنَّ أَكْرَمَكُمْ عِندَ ٱللَّهِ أَتْقَىٰكُمْ ۚ إِنَّ ٱللَّهَ عَلِيمٌ خَبِيرٌۭ

4624 ٱجْتَنِبُوا۟ كَثِيرًۭا مِّنَ

4624 ٱلظَّنِّ إِثْمٌۭ ۖ وَلَا

4624 إِنَّ ٱللَّهَ تَوَّابٌۭ رَّحِيمٌۭ

and sadly there are more.

(Numbers are obtained from http://api.alquran.cloud/v1/juz/26/quran-uthmani)

**Comment by meezaan** [comment] 2020-05-21 05:33
So this is very interesting - https://alquran.cloud/ayah/4612/quran-uthmani does not show the 'additional' meems  when displaying with the font - but the raw response has them. So me-quran must be a super intelligent font!

Leave it with me - I will create a new edition in the API with https://github.com/khaledhosny/quran-data.

**Comment by vipafattal** [comment] 2020-05-21 14:16
Thank for this amazing effort & details, I will test it and push it to beta users

**Comment by meezaan** [comment] 2020-06-09 05:15
This may very well be a font display issue related to a proposal like https://www.unicode.org/L2/L2017/17377-proposal-tanwin-inline.html. We are investigating further.

**Comment by vipafattal** [comment] 2020-07-06 21:37
Salaam brother
While using `kitab-bold` font with `quran-unicode` Quran edition, it turns out to they are not fully compatible with each other [see](https://github.com/quranacademy/kitab-font/issues/7#event-3517430168). 
The Kitab designer team recommends using Kitab fonts with [this](https://github.com/quranacademy/kitab-font/issues/7#issuecomment-654434899) Quran edition, so is this version available in the API? If not can is it possible to be added.

**Comment by vipafattal** [comment] 2020-07-06 21:48
@meezaan 
one more thing, Do you think using the aforementioned Quran edition, will open up another old [issue](https://github.com/islamic-network/api.alquran.cloud/issues/31), because of the known issues in that [version](https://github.com/quranacademy/quran-text#known-issues).

**Comment by meezaan** [comment] 2020-07-07 02:56
Alaykum salaam @vipafattal worth trying. I will add it to the API.

I also have some ideas on how to fix this issue, but I need a good few hours of time to try them out.

I will try and add the edition for you this week insha'Allah.

**Comment by meezaan** [comment] 2020-07-12 06:43
Al Salaamu Alaykum @vipafattal. The edition has been added. You can access it via 'quran-uthmani-quran-academy'. For example: https://api.alquran.cloud/v1/ayah/2:4/quran-uthmani-quran-academy.

**Comment by meezaan** [comment] 2020-07-12 12:11
@vipafattal I have spent some time on this today. The changes I had thought I might make to quran-uthmani are already the ones made by Quran Academy. The problem is that these changes make it impossible for most of the fonts to render some parts of the text, except for Kitab.

The solution, of course, is to fix the fonts. I've mentioned somewhere else in another issue that this likely happened around 2016 after some proposed changes to the way Arabic was rendered within unicode, before that the text from Tanzil.net would have worked fine.

I have also created https://alquran.cloud/arabic-font-edition-tester to test various fonts and editions. The working combinations are Quran ME 2 with quran-uthmani and and Kitab / Kitab Bold with quran-uthmani-quran-academy.

Please test the new combination (I've already applied it to the web app to see how it works). If it works for you, we can close this issue. 

In due course, it may be that we open another issue to fix an existing Uthmanic font to render quran-uthmani-quran-academy properly (something that is closer to Uthmani calligraphy than Kitab / Scheherazade).

FYI - I've seen some of these unicode issues even in the printed Qur'ans. The only place I don't see them (naturally) is in hand-written (more like retraced) ones from Turkey or lithographic type prints of hand written sub-continent editions.

Insha Allah, I hope this helps.

**Closed** 2020-07-12 12:17 UTC

**Comment by meezaan** [comment] 2020-07-13 05:24
@vipafattal Even the Droid Kufi, Droid Naskh and Amiri (about 80% there) fonts work fine, although one has to wonder why the Droid family was invented - it's almost an insult to the beauty of the Arabic language.
